name: CI

on:
  push

jobs:
  Automation:
    runs-on: ubuntu-latest

    steps:
    - name: Initialization
       run: echo "Initialization"

    - name: Check out
      uses: actions/checkout@v2
    
    - name: install dependencies
       run: npm install