name: CI

on:
  push

jobs:
  Automation:
    runs-on: ubuntu-latest

    steps:
    - run: echo "Initialization"
    - uses: actions/checkout@v3
    - run: npm install
    - run: npm test
    - run: zip -r result.zip automation.json
    - run: |
        curl -X POST https://api.zephyrscale.smartbear.com/v2/automations/executions/cucumber?projectKey=PLT&autoCreateTestCases=false \
        -H 'Authorization: Bearer ${{ secrets.ZSCALETOKEN }}' \
        -F 'file= @result.zip' \
        -F 'testCycle="{\"Name\": \"Test cycle 1\", \"Description\": \"descripcion 2\"}";type=application/json'

    
    
