# This is a basic workflow that is manually triggered

name: Manual workflow

on:
  push:
    branches:
      - master


jobs:
  automation:
    runs-on: ubuntu-latest

    steps:
    - name: Initializacion
      run: echo "Inicializacion de la Ejecucion"

    - name: Checkout
      uses: actions/checkout@master
    
    - name: Install dependencies
      run: npm install
    
    - name: Run test command
        run: npm run test 


