name: CI

on:
  push

jobs:
  Automation:
    runs-on: ubuntu-latest

    steps:
    - run: echo "Initialization"
    - uses: actions/checkout@v3
    - run: npm install
    - run: npm test
    - run: zip -r result.zip automation.json

    
    
