name: CI

on:
  push

jobs:
  Automation:
    runs-on: ubuntu-latest

    steps:
    - name: Initialization
    - run: echo "Initialization"
    
    - name: checkout 
    - uses: actions/checkout@v3
    
    - name: Install dependencies
    - run: npm install
    
    
